graph TD
    A[Software_en_desarrollo] --> B[Areas_de_riesgo]
    B --> C[Riesgo_funcional]
    B --> D[Riesgo_tecnico]
    B --> E[Riesgo_integracion]
    B --> F[Riesgo_performance]
    B --> G[Riesgo_seguridad]

    C --> C1[Tests_de_requisitos]
    D --> D1[Tests_de_codigo]
    E --> E1[Tests_de_integracion]
    F --> F1[Tests_de_carga]
    G --> G1[Tests_de_seguridad]
